<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/reset-backend.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=$this->siteConfig('libUrl')?>/admin/style/backend.css" type="text/css" media="screen" rel="stylesheet">

<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/brick/toolbar/toolbar.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/brick/action-title/action-title.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/brick/action-menu/action-menu.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/app/data.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/tab/tab.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=$this->siteConfig('extUrl')?>/prompt/prompt.css" type="text/css" media="screen, projection">
<? echo $this->headLink() ?>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/jub.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/jquery.ndd.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/ckeditor4/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/brick/toolbar/toolbar.min.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/brick/action-menu/action-menu.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/tab/tab.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/prompt/prompt.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('libUrl')?>/script/icon-selector.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('libUrl')?>/script/ckeditor.js"></script>
<? echo $this->headScript() ?>
<script>
/************************************/
/*Declear Global Javascript Items****/
/************************************/
var WB;
var FINDER;
var EventMessenger = {};
_.extend(EventMessenger, Backbone.Events);

window.ORG_CODE = "<?php echo $this->siteConfig('organizationCode')?>";
window.SITE_FOLDER = "<?php echo $this->siteConfig('remoteSiteId')?>";
</script>
