<?php
$csu = Class_Session_User::getInstance();
$naviArr = array(
	'left' => array(
		array('title' => '修改密码', 'url' => '/'.$csu->getUserId().'/user/index/password')
	),
	'right' =>array(
		array('title' => '我的账户', 'url' => '/'.$csu->getUserId().'/user')
	)
);
?>

<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<link type="text/css" href="<?=Class_Server::extUrl()?>/reset-backend.css" media="screen" rel="stylesheet">
	<link type="text/css" href="<?=Class_Server::extUrl()?>/common-extension.css" media="screen" rel="stylesheet">
	<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/jub.js"></script>
	<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/common-extension.js"></script>
	
	<title><?=$this->pageTitle ?></title>
</head>

<body>
	<?php echo $this->extension('Navi', $naviArr)?>
	<br />
	<br />
	<div class='body_main_frame'>
		<div class='whitebox'><div class='content'>
			<div class='action-menu'>
				<?php echo $this->extension('ActionMenu', $this->actionMenu) ?>
			</div>
			<div class='flash-message'>
	<?php 
		$messenger = new Zend_Controller_Action_Helper_FlashMessenger();
		$messages = $messenger->getMessages();
		if(count($messages) > 0) {
	?>
				<div class='brick-admin-flash-message'>
	<?php	
			foreach($messages as $m) {
				echo "<div>".$m."</div>";
			}
	?>
				</div>
	<?php 
		}
	?>
		</div>
			<?php echo $this->layout()->content ?>
		</div></div>
	</div>
</body>
</html>