<div class='datalist'>
	<table class='datalist'>
		<thead>
			<tr class='title-row'>
				<th>组织名</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
	<ul id='datalist-paginator'>
	</ul>
</div>

<script>
	window.restUrl = '/rest/org'
</script>

<script type='text/template' id='data-row'>
<td>
	{{data.orgName}}
</td>
<td>
	<a href='/admin/org/edit/id/{{data.id}}'>编辑</a>
	<a href='/admin/remote-user/index/orgCode/{{data.id}}'>账户管理</a>
</td>
</script>


<script data-main="<?=Class_Server::extUrl()?>/app/data" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>
